---
config:
  layout: dagre
  themeVariables:
    fontSize: 22.5px
---
flowchart TD
 subgraph Actors["Actors"]
        A1["Bhen"]
        A2["Jhustin"]
  end
 subgraph System["MC Tunes System"]
        UC15(("Use Case #15: Developer Testing Environment"))
        UC2(("Use Case #2: User Feedback"))
        UC4(("Use Case #4: Adding/Removing User Permissions"))
        UC10(("Use Case #10: Fixing Existing Bugs"))
        UC16(("Use Case #16: Developing User Demanded Features"))
        US11(("Story #11: Dev Version of Website"))
   
  end
    A1 --> UC15
    A2 --> UC15
    UC15 --> UC2
    UC15 --> UC4
    UC15 --> UC10
    UC15 --> UC16
    UC15 --> US11
