---
config:
  layout: dagre
  themeVariables:
    fontSize: 22.5px
---
flowchart TD
 subgraph Actors["Actors"]
        A1["Jaquan"]
        A2["Boris"]
  end
 subgraph System["MC Tunes System"]
        UC2(("Use Case #2: User Feedback"))
        US7(("Story #7: Easy way to report issues/bugs"))
        US18(("Story #18: User Feedback"))
  end
    A1 --> UC2
    A2 --> UC2
    UC2 --> US7
    UC2 --> US18
